### ISSUE TITLE
CSS文件中 @charset 要不要写？

### ISSUE THREAD

**Issue by cyjake** [thx/cube#10]
> 在外部样式表中最多有一个@charset规则可以出现——它不可以出现在嵌套的样式表中，也必须出现在文档的最开始，且前面没有任何字符。在"@charset"之后，用户指定字符编码的名称。
- [在 Chrome Safari 中，如果一段 CSS 代码（无论是外部文件还是页内嵌入）的 '@charset' 规则之前有非空白字符或注释的内容存在，那么该规则之后的一个规则集将失效。](http://www.w3help.org/zh-cn/causes/RN5001) **Chrome 已修复！**
- [RN8002: 各浏览器在 HTML 页面与页面中引入的外部 CSS 文件编码不一致时表现不同](http://www.w3help.org/zh-cn/causes/RN8002)
## 结论

为了避免HTML和CSS文件编码不同时造成的中文解析乱码，请在CSS文件头部加上指定的`@charset`，例如：

``` css
@charset "utf-8";
```

**Comment by cyjake** [comment]
合并的时候要小心处理

**Comment by cyjake** [comment]
合并的时候将移除各个模块中的 `@charset`，最终生成的 cube.css 头部有没有必要加呢

**Comment by cyjake** [comment]
待测试：在 IE 中引用 http://g.tbcdn.cn/thx/cube/1.2.0/cube.css 文件会如何

**Comment by yisibl** [comment]
最终结论整理到：[《CSS 创作指南》](https://github.com/yisibl/css-creating)
