### ISSUE TITLE
增加使用了cube的网站展示

### ISSUE THREAD

**Issue by jserme** [thx/cube#3]
简单的链接列表就行
- xxx 著名的IT博客......
- momo NB的网站

**Comment by yisibl** [comment]
http://jser.me/ 怎么样？(_^__^_)

**Comment by jserme** [comment]
@yisibl 我都不写东西了，找点有名的站，推荐他们用一下

**Comment by cyjake** [comment]
胡伯老师弃笔的话是前端界的巨大损失啊
