### ISSUE TITLE
a 和 button 作为按钮时，样式不统一

### ISSUE THREAD

**Issue by huanglong-zz** [thx/cube#6]
按钮如果是 a 标签时，hover 样式有一个下划线

**Comment by cyjake** [comment]
cube 里的 a:hover 下划线是用 border-bottom 实现的，这个做法有好有坏，可以讨论一下

**Comment by cyjake** [comment]
瓜老师 demo 补得真快 http://thx.github.io/cube/demo/button/

可以看出高度也不一致，button.css 还有不少优化空间

**Comment by cyjake** [comment]
https://github.com/dotnil/brix-style/blob/scss/scss/button.scss

**Comment by yisibl** [comment]
已完成
https://github.com/thx/cube/commit/e3def160320d534e1e3cbac0eecec44590e5ebef
