### ISSUE TITLE
禁用中文输入法失效

### ISSUE THREAD

**Issue by huanglong-zz** [thx/cube#8]
不是很清楚这个的应用场景，不过我 在 demo 里，依然可以在 input 中输入中文：

``` html
<input class="ime-disabled" type="text" placeholder="禁用中文输入">
```

![image](https://f.cloud.github.com/assets/670360/1528385/045553e0-4c0a-11e3-8a5a-4ecb42db9ee5.png)

**Comment by yisibl** [comment]
该属性 WebKit 不支持，抱歉暂时文档不全 [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/ime-mode)

**Comment by cyjake** [comment]
+文档 +注释 说明一下
